name: app_pesquisa_de_satisfacao
description: Provida pesquisa de satisfação.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:       # Required for every Flutter project
    sdk: flutter # Required for every Flutter project

  cupertino_icons: ^1.0.2 # Only required if you use Cupertino (iOS style) icons
  sqflite: ^2.0.0+3
  idb_sqflite: ^1.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
<<<<<<< HEAD
  redux: ^5.0.0
=======
  flutter_redux: ^0.8.2
  redux: ^5.0.0
  provider: ^6.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
>>>>>>> 280f87b0d03843ed235dbb6d9c6f5fc6d1f7e9ef

dev_dependencies:
  flutter_test:
    sdk: flutter

  path_provider: ^2.0.2
  hive_generator: ^1.1.0
  build_runner: ^2.0.5
  path: ^1.8.0
  flutter_redux: ^0.8.2

flutter:

  uses-material-design: true

  assets:
      - assets/images/provida_logomarca.png

  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf